name: build

on:
  #pull_request:
  #  branches:
  #    - main
  push:
    tags:
      - "v*"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

env:
  IMAGE_VERSION: ${{ github.ref_name}}
  IMAGE_TAG_BASE: "${{ vars.DOCKER_DAPRIO_REGISTRY }}/daprio/dapr-kubernetes-operator"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: check-out
        uses: actions/checkout@v3
      - name: Container Registry login
        uses: docker/login-action@v2
        env:
          DOCKER_REGISTRY_ID: ${{ vars.DOCKER_DAPRIO_REGISTRY }}
        with:
          username: ${{ secrets.DOCKER_REGISTRY_ID }}
          password: ${{ secrets.DOCKER_REGISTRY_PASS }}
      - name: Build Operator Container Image
        run: |
          export VERSION="${IMAGE_VERSION#v}"

          make bundle docker-build docker-push
      - name: Build Operator Bundle
        run: |
          export VERSION="${IMAGE_VERSION#v}"

          make bundle bundle-build bundle-push
      - name: Build Operator Catalog
        run: |
          export VERSION="${IMAGE_VERSION#v}"

          make catalog-build catalog-push
